colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = true

[homepage]
  layout = "profile"
  homepageImage = ""
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = false
  showBreadcrumbs = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showSummary = true
  sharingLinks = []
  showPagination = true
  showRelatedContent = true
  relatedContentLimit = 3
  showComments = false

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  showTaxonomies = true
  showSummary = true
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true
  cardView = false
